spring:
  application:
    name: DocCaseTracker

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpirationMs: 900000 # 15 minutes
    refreshTokenExpirationMs: 604800000 # 7 days
    issuer: DocCaseTrackerSecurity

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.doccasetracker: DEBUG

server:
  port: 8081


kind: Application